### ISSUE TITLE
Remaster Update and UUIDs

### ISSUE THREAD

**Issue by OmegaRogue** [TikaelSol/PF2e-Psychic-Amps#10]
The spells currently still are at pre remaster state, they need to be updated. Also, the spells have the same uuid as the default spells, I'm not sure if thats intended, but it messes with some automation

**Comment by TikaelSol** [comment]
The only remaster spells included are figment, ignition, and frostbite. Other things have had their errata applied (except ray of frost and produce flame since those are moot anyways). Also it is impossible for the UUID to be the same in a module and the system, since the module name is part of the UUID. If you mean the ID then yes that is intended, but shouldn't mess with anything system side.

**Comment by OmegaRogue** [comment]
> The only remaster spells included are figment, ignition, and frostbite. Other things have had their errata applied (except ray of frost and produce flame since those are moot anyways). Also it is impossible for the UUID to be the same in a module and the system, since the module name is part of the UUID. If you mean the ID then yes that is intended, but shouldn't mess with anything system side.

Yes, i mean the source ID (and slug), which results in not being able to use things like action support engine and reaction checker to add automation for the psychic versions of the spells

**Comment by UrsaNoctua** [comment]
> Other things have had their errata applied (except ray of frost and produce flame since those are moot anyways).

I think a couple errata may have been missed.

I was just reworking my psychic character using version 2.0.2 of the module.  I noticed that telekinetic projectile still has the pre-remaster damage (1d6+mod instead of 2d6).  I also noticed that the text for Shield and Mage Hand haven't been updated (although the Mage Hand changes have no mechanical impact).

Are there instructions for how to update the packs in the module?  I'm happy to give these updates a go and submit a PR.
